name: wp_json_api
description: WordPress and WooCommerce JSON API for Flutter Mobile. API allows you to login, register new users, get users info and more.
version: 0.1.0
homepage: https://woosignal.com
repository: https://github.com/woosignal/wp-json-api-flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
